version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    profiles:
      - app

  frontend:
    container_name: frontend
    build:
      context: ./nodejs-experiment-fe
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nodejs-experiment-fe/:/frontend
    profiles:
      - app

  repo:
    container_name: repo
    image: mongo
    ports:
      - 27017:27017
    profiles:
      - platform
