version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    profiles:
      - app
      - be

  frontend:
    container_name: frontend
    build: ./nodejs-experiment-fe
    ports:
      - 80:80
    profiles:
      - app
      - fe

  repo:
    container_name: repo
    image: mongo
    ports:
      - 27017:27017
    profiles:
      - platform
